### PR TITLE
High quality images (svg)

### PR DESCRIPTION
**Pull request by coder26-cmd**
Hello! 
In issue #2 it was said, that images are low quality. What I fixed is changed .png images to .svg in images/ folder. Now, flags look better. I hope you'll like this.

### CODE REVIEW

**Comment by VFDan** [comment]
Could you possibly remove the extra whitespace? This is especially noticable in `ba.svg`, where the stars go outside the flag (in the actual flag the ones at the end are only half-stars 
image

**Comment by coder26-cmd** [comment]
Ok, I will try.

**Comment by coder26-cmd** [comment]
Fixed spaces in the following countries' flags:
- Bosnia And Herzegovina
- Saint Kitts And Nevis
- United Kingdom
- Burundi
- Namibia
- Tuvalu
- Fiji
- Tanzania
- Solomon Islands
- Turkmenistan
- Jamaica

**Comment by VFDan** [comment]
There's still a lot of extra whitespace in other flags...
image
If you don't want to fix all of them, I was actually in the middle of updating all the flags anyway.

**Pull request merged**
